services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./Clients/backend:/app/Clients/backend
      - ./Servers:/app/Servers
    environment:
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
      - AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT=${AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT}
      - FILESYSTEM_ROOT=/app/Resume-Builder
    command: gunicorn --bind 0.0.0.0:5001 "Clients.backend.app:app"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./Clients:/app/Clients
      - ./Servers:/app/Servers
    environment:
      - BACKEND_URL=http://backend:5001
    command: streamlit run Clients/streamlit_ui.py
